name: Linting

on:
  push:
    paths:
    - "cesium_ion/**"
    - ".github/workflows/lint.yaml"
  pull_request:
    types: [opened, synchronize, edited]


jobs:

  Check-code-quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install -r requirements/testing.txt
          pip install pylint pycodestyle flake8

      - name: flake8 Lint
        run: flake8 cesium_ion

      - name: Pycodestyle
        run: make pycodestyle
